### ISSUE TITLE
Setup CI with GitHub for running the collator node

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/pendulum#12]
Action items:
- [x] Setup a runner on gcloud to build a docker image from the latest tag
- [x] Integrate with GH actions
- [ ] Document the process in Notion

**Comment by xiuxiu62** [comment]
Added event handler to gcp instance, but still need to work out deployment steps

**Comment by erasmus** [comment]
@gonzamontiel 2 questions:

1. Why would we only document in Notion? 
2. Should this ticket be in doing?

**Comment by gonzamontiel** [comment]
> @gonzamontiel 2 questions:
> 
> 1. Why would we only document in Notion?
This was for internal devops purposes.

> 2. Should this ticket be in doing?

We need to close this ticket since we are opting for a different approach now.
