### ISSUE TITLE
Create migrations for changed CurrencyId enum

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#147]
TODO: we still need to figure out what exactly has to change and how. 

This is related to [this](https://github.com/pendulum-chain/spacewalk/issues/283) ticket.

**Comment by ebma** [comment]
Maybe this can be skipped if we change the CurrencyId enum in a certain way.

**Comment by TorstenStueber** [comment]
@ebma We can close this ticket now that we replace `ForeignCurrencyId` with `u8`, correct?

**Comment by ebma** [comment]
Yes, we can close this ticket because no migrations are required. I created a follow-up ticket to change the definitions of the `CurrencyId` in amplitude and foucoco #152.
