### ISSUE TITLE
Enable Dependabot version updates

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#150]
Use dependabot to check once a day whether any of our dependencies require version updates or contain vulnerabilities.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/150?planning-poker) with Zenhub @TorstenStueber @ebma

**Comment by TorstenStueber** [comment]
Done. Enabled for all repositories using https://docs.github.com/en/code-security/dependabot/dependabot-alerts/configuring-dependabot-alerts#managing-dependabot-alerts-for-your-organization.
