### ISSUE TITLE
Add benchmarks for custom pallets per runtime

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#178]
We should consider benchmarking the custom pallets (spacewalk + orml-extension) for each of our runtimes separately. The default_weights that are included by the pallets were generated on a standalone chain, and the configuration parameters between that test chain and our parachains might differ such that also the resulting weights differ. That's why, for maximum security we should consider re-generating these weights for each of our runtimes. 
This entails:
- [x] Setting up the Foucoco, Amplitude and Pendulum runtime for benchmarking, 
- [x] Running the benchmarks for our custom (spacewalk + orml-extension) pallets to generate the weights, and
- [x] Specifying the generated weights in the respective pallets configurations of the runtimes.

**Comment by prayagd** [comment]
Moving to review
