### ISSUE TITLE
Execute Amplitude upgrade with implementation of Contract API for runtime

### ISSUE THREAD

**Issue by RustNinja** [pendulum-chain/pendulum#186]
Issue related to https://github.com/pendulum-chain/pendulum/issues/184.
Even after redeployment of Amplitude node with this [changes](https://github.com/pendulum-chain/pendulum/pull/165/files#diff-f4b42f005d53041fa8c231b4d2e543992c0dd78fce79e2e11d18069b7b58be63) we still need execute runtime upgrade.

To enable contracts for amplitude we also need to execute the Amplitude runtime upgrade that implement Contract API.
From main branch
At least this commit : https://github.com/pendulum-chain/pendulum/commit/cfed74386a92f20c78de770b04eb07060d02f79f
[Merged PR](https://github.com/pendulum-chain/pendulum/pull/165/files#diff-f4b42f005d53041fa8c231b4d2e543992c0dd78fce79e2e11d18069b7b58be63)

**Comment by TorstenStueber** [comment]
@RustNinja why is this a ticket on the Pendulum repo? Exe
