### ISSUE TITLE
Add vesting manager pallet to Amplitude

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/pendulum#202]
### Requirement
In certain cases, there is a need for the project team to retract the tokens that have been distributed to an account e.g. Ice Berg nodes' sub-identity account.

### Solution
Add vesting manager pallet to the Amplitude runtime. This has already been added to the Pendulum runtime as per this PR.

**Comment by vadaynujra** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/202?planning-poker) with Zenhub @TorstenStueber

**Comment by TorstenStueber** [comment]
See https://github.com/pendulum-chain/pendulum/pull/126 as a reference.
