### ISSUE TITLE
Add Zenlink RPC to pendulum node

### ISSUE THREAD

**Issue by RustNinja** [pendulum-chain/pendulum#217]
[Zenlink UI](https://dex.zenlink.pro/#/swap) will support interface by default if substrate chain expose Zenlink-protocol endpoinds

Requirements:
-  add dependency to zenlink-protocl-api to pendulum-node
- add trait bound as `ZenlinkProtocolApi` for `create_full_pendulum`, `create_full_amplitude` and `create_full_foucoco` functions inside rpc.rs

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/217?planning-poker) with Zenhub @RustNinja @TorstenStueber @ebma
