### ISSUE TITLE
Update runtimes to `polkadot-v0.9.40` 

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#219]
We should update our runtime dependencies to version `polkadot-v0.9.38` so that we get rid of some dependency conflicts.
For example, we were running into problems because our spacewalk pallets use `jsonrpsee` with version >0.16.0 but other parachain pallets that are on `polkadot-v0.9.37` still use `jsonrpsee` version 0.15.x (e.g. Zenlink) which then leads to conflicts when importing RPC modules from their pallets.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/219?planning-poker) with Zenhub @ashneverdawn @ebma @RustNinja @TorstenStueber

**Comment by TorstenStueber** [comment]
Maybe it makes sense to even switch to Polkadot version 0.9.40 now – it is already supported by orml.

This would also require a follow up task to not just execute the runtime upgrade but first to redeploy all of our collator nodes.

**Comment by vadaynujra** [comment]
Updated version in title to `v0.9.40`

**Comment by TorstenStueber** [comment]
I created a `polkadot-v0.9.40` branch in substrate-stellar-sdk repository so that we are good to go from that side. Probably also need to update dependencies in the other related dependencies:
* https://github.com/pendulum-chain/oracle-pallet
* https://github.com/pendulum-chain/Zenlink-DEX-Module
* https://github.com/pendulum-chain/bifrost

**Comment by TorstenStueber** [comment]
For that reason I want to re-estimate. @vadaynujra is such a feature not available (change an estimate)?

**Comment by b-yap** [comment]
@TorstenStueber  including https://github.com/pendulum-chain/spacewalk, right?

**Comment by b-yap** [comment]
Yes I would think this will be higher than 3. The jump from .37 to .40 is huge. 

A few changes I found: 
* [rename grandpa crates](https://github.com/paritytech/substrate/commit/7c8b89b3a6b603902709fc33fdb10a864b8b4204)
* [rename random-collective-flip crates](https://github.com/paritytech/substrate/pull/13301)
* Weight's `from_ref_time()` is deprecated, so we have to rerun that one again

And there's plenty more. 
Currently on https://github.com/pendulum-chain/oracle-pallet.

**Comment by TorstenStueber** [comment]
@b-yap yes, also including Spacewalk of course. Seems like I have the power to change the estimate. Shall we change it to 5 then @b-yap, or even 8?

**Comment by b-yap** [comment]
8 would be fine.

**Comment by TorstenStueber** [comment]
Alright, done.

**Comment by Curu24** [comment]
Hello, will this include `--rpc-relay-chain-url` functionality?

**Comment by TorstenStueber** [comment]
@Curu24 Is this a new feature introduced in Substrate recently? Can you refer to it please?

**Comment by Curu24** [comment]
> @Curu24 Is this a new feature introduced in Substrate recently? Can you refer to it please?

https://github.com/paritytech/cumulus/pull/1585

**Comment by Curu24** [comment]
> Since this feature has been merged already many months ago, it is already included in the [`polkadot-v0.9.31` branch](https://github.com/paritytech/cumulus/tree/polkadot-v0.9.31).
> 
> So, it looks to me like the Pendulum nodes would already include this functionality even without this PR.

Oh, yes, sorry. You're right. I was trying with the older release 0.9.29. With 0.9.37 it works.
