### ISSUE TITLE
Add and configure spacewalk pallet for runtime

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#22]
We need to add and configure the spacewalk pallet for our pendulum chain. This includes the following tasks:

- [x] Add the spacewalk pallet to the Cargo.toml. Since it is not published to crates.io just specify the repository in Cargo.toml and maybe specify a proper tag (that has to be created first) or a commit hash to make it stick to a specific version even if the main branch of the spacewalk repo changes.
- [x] Configure the pallet in the runtime. Have a look at how this is done in the [spacewalk testchain](https://github.com/pendulum-chain/spacewalk/blob/main/testchain/runtime/src/lib.rs). 
- [ ] Check if calling the pallets extrinsic works. To do so, run the pendulum parachain locally after adding the pallet, (a guide on how to do this with pendulum-launch is [here](https://pendulum.gitbook.io/pendulum-docs/build/using-pendulum-launch/launch#launching-a-local-pendulum-chain)). For the `report_stellar_transaction` extrinsic you might have to write a small Rust script that takes a Stellar transaction, converts it to the xdr and prints out the bytes in hexadecimal (some inspiration might be drawn from the vaults [deposit.rs](https://github.com/pendulum-chain/spacewalk/blob/main/clients/vault/src/deposit.rs) code). For the `redeem` extrinsic you might have to use the address conversion tool from https://prototype.pendulumchain.org/balances to get the binary representation for the `stellar_vault_pub_key` field.

**Comment by xiuxiu62** [comment]
I'm running into dependency version errors when including pallet-spacewalk in the runtime pallet.  The issue is in selecting a version of parity-util-mem for sp-core.  If anyone has run into something similar and has suggestions, it would be greatly appreciated.

**Comment by ebma** [comment]
Is this error preventing you from including the spacewalk pallet in the runtime or are you just unable to compile spacewalks vault client?

**Comment by xiuxiu62** [comment]
the former, i'm blocked until pendulum deps are bumped to polkadot 0.9.18.  Going to work on that today

**Comment by xiuxiu62** [comment]
I'm now working off of pr [#25](https://github.com/pendulum-chain/pendulum/pull/25), which resolves a number of compilation errors.
