### ISSUE TITLE
Lower TransactionByteFee configuration

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#233]
The TransactionByteFee of pallet-transaction-payment determines how much transaction fee to pay per byte of the extrinsic.

Since some extrinsics for Spacewalk are very big (a few 100KB as they contain a whole Stellar block), we would need to lower this setting as these extrinsics would become prohibitively expensive.

- [ ] lower TransactionByteFee from 10 micro units to 100 nano units (i.e., a factor of 100)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/233?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber
