### ISSUE TITLE
Bump to Polkadot v0.9.18

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/pendulum#24]
Bump dependencies to [v0.9.18](https://github.com/paritytech/polkadot/releases/tag/v0.9.18). This will allow us to start integrating code from Spacewalk in that same version.

**Comment by xiuxiu62** [comment]
I'm realizing that some idents that don't exist in 0.9.18 aren't being rendered by rust's language server protocol, if they're being used or implemented inside of a declarative macro.  As an example, on line 604 of runtime/src/lib.rs, we can see a Trait implementation that doesn't exist in the used version of cumulus_primitives_core
```rs
impl_cumulus_primitives_core::CollectCollationInfo<Block> for Runtime {
    fn collect_collation_info(header: &<Block as BlockT>::Header) -> cumulus_primitives_core::CollationInfo {
    ParachainSystem::collect_collation_info(header)
    }
}
```

**Comment by ne-manya** [comment]
All good now, I managed to fix all the errors and bump the version. Making a PR right now.
