### ISSUE TITLE
Extract `chain_extension` implementation and re-use it in all runtimes

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#249]
We want to use the same `chain_extension` implementation in all our runtimes. In order not to duplicate any code, we should extract the implementation of the `chain_extension` into another directory, similar to what Astar did [here](https://github.com/AstarNetwork/Astar/tree/master/chain-extensions), and re-use that in each runtime.

To add a bit more structure, we can even split our current chain extension into two sub-parts: a 'token-extension' which is comprised of the functions with ID 1100-1199 and a 'price-extension' which consists of functions with ID 1200-1299. Astar also found a way to use register three chain extensions at the same time, see [here](https://github.com/AstarNetwork/Astar/blob/51873938c8d63cc87885db95af74cfb3ec36d015/runtime/shibuya/src/lib.rs#L683-L687).

**Comment by ebma** [comment]
@pendulum-chain/product this ticket should be prioritized soon. Having this for before Nabla launch would be good, because otherwise we have to duplicate code once we want to use our Solidity wrapper contract solution also on Pendulum.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/249?planning-poker) with Zenhub @adelarja @b-yap @ebma @TorstenStueber

**Comment by TorstenStueber** [comment]
@prayagd @ebma can we move this ticket to Ready? Any reason why not?

**Comment by ebma** [comment]
We can move it already but should only work on it once #356 is merged.

**Comment by prayagd** [comment]
@ebma just to check this is important for the Nabla mainnet launch right?

**Comment by ebma** [comment]
It's a chore and so is not a stopper for anything. It's about refactoring some code and wouldn't add or remove any functionalities. We should still do it eventually and I wouldn't like to have it in the icebox.
