### ISSUE TITLE
Prepare Pendulum runtime upgrade to spec version 8

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#252]
Bump Pendulum runtime version to 8.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/252?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber
