### ISSUE TITLE
Prepare Foucoco runtime upgrade to include ZenlinkLPToken changes in the runtime

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#255]
We should test that the ZenlinkLPToken type that we added to the `CurrencyId` enum works as expected on Foucoco. So we should do a runtime upgrade that includes these changes.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/255?planning-poker) with Zenhub @ebma @adelarja @TorstenStueber

**Comment by ebma** [comment]
Closing this because the changes were included in #282.
