### ISSUE TITLE
Audit: PDM-010 - Employment of Sudo Pallet

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/pendulum#258]
The current implementation of the sudo FRAME pallet in the runtime employs it as an alternative to the governance mechanism.

ID PDM-010
Scope Decentralization
Status New

**Description**
The sudo pallet is integrated into the runtime configuration: `runtime/foucoco/src/lib.rs:1509`:
```
 construct_runtime!(
pub enum Runtime where Block = Block,
         NodeBlock = opaque::Block,
         UncheckedExtrinsic = UncheckedExtrinsic,
     {
         /* ... */
         // Governance
         Sudo: pallet_sudo::{Pallet, Call, Storage, Config<T>, Event<T>} = 12,
         /* ... */
} );
```
The root account, initially set at genesis, is defined as follows: `node/src/chain_spec.rs:229`: `let sudo_account =
pallet_multisig::Pallet::<foucoco_runtime::Runtime>::multi_account_id(&signatories[..], 3);`
This configuration allows the use of the ensure_root method for operations such as `add_allowed_currencies` and `remove_allowed_currencies`. Although there is no immediate security risk associated with this setup, it raises concerns regarding potential centralization.

**Recommendation**
Utilizing a root account for governance purposes is considered a less favorable design choice due to its potential for centralization and the security risks associated with compromised private keys.
To address this issue, we recommend the following actions:
1. Comprehensive Documentation: It is crucial to thoroughly document the intended use of the sudo pallet and the root account within the project. This documentation should provide clear explanations of the potential risks and limitations associated with their usage. Both the development team and end-users should be adequately informed to ensure transparency and informed decision- making. If there are plans to deactivate the sudo functionality after the network launch, a detailed process similar to the sudo removal outlined by Polkadot should be documented.
2. Auditing and Monitoring: Prior to the removal of the sudo pallet, it is essential to establish regular auditing and monitoring processes. These measures will help ensure that the sudo pallet and the root account are not misused or compromising the system's security. By conducting thorough audits and continuous monitoring, any potential vulnerabilities or misuse can be identified and addressed promptly.
By following these recommendations, you will mitigate potential centralization concerns and enhance the overall governance and security aspects of the project.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/258?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber

**Comment by ebma** [comment]
I would ignore and close this ticket. We only use SUDO on Foucoco and we do that for good reason. We're aware of the implications which is why we don't use it on our 'main'-chains.
