### ISSUE TITLE
Audit: PDM-008 - Hardcoded Constants in match

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/pendulum#260]
The presence of hardcoded constants in the match statement within the implementation of ChainExtension hampers code readability.

ID PDM-008
Scope Code Quality
Status New

**Description**
The following code segment has drawn our attention: `runtime/foucoco/src/lib.rs:964`:
```
match func_id { //transfer
     1105 => { /* ... */ },
     //balance
     1106 => { /* ... */ },
     //total_supply
     1107 => { /* ... */ },
     //approve_transfer
     1108 => { /* ... */ },
     //transfer_approved
     1109 => { /* ... */ },
     //allowance
     1110 => { /* ... */ },
     //dia price feed
     7777 => { /* ... */ },
     _ => { /* ... */ },
}
```
While the code comments provide some understanding of the functionality associated with each func_id , it is recommended to enhance
the code logic in this section to improve comprehensibility, rather than solely relying on comments.

**Recommendation**
We recommend creating a separate enum to handle all the supported func_id options, using descriptive names that correspond to each function. This approach enhances code readability and maintainability:
```
enum FuncId { Transfer,
     Balance,
     TotalSupply
     ApproveTransfer,
     TransferApproved,
     Allowance,
     DiaPriceFeed,
}
impl TryFrom<u16> for FuncId {
     type Error = DispatchError;
     fn try_from(func_id: u16) -> Result<Self, Self::Error> {
          let id = match func_id {
               1105 => Self::Transfer,
               1106 => Self::Balance,
               1107 => Self::TotalSupply, 
               1108 => Self::ApproveTransfer, 
               1109 => Self::TransferApproved, 
               1110 => Self::Allowance,
               7777 => Self::DiaPriceFeed,
                _ => {
                      error!("Called an unregistered `func_id`: {:}", func_id);
                      return Err(DispatchError::Other("Unimplemented func_id")) 
               }
          };
          Ok(id) 
     }
}
```
This enum allows for easier handling of the logic within the match statement in the call implementation.
Furthermore, it is good practice to implement the logic for each function in a separate method instead of encapsulating all the code within the match arms. This promotes code modularity and readability.
Here's an example of how the code would look with the recommended changes:
```
let func_id = FuncId::try_from(env.func_id())?; match func_id {
     FuncId::Transfer => /* Call method that performs transfer */,
     FuncId::Balance => /* Call method that returns balance */,
     FuncId::TotalSupply => /* ... */ ,
     FuncId::ApproveTransfer => /* ... */,
     FuncId::TransferApproved => /* ... */,
     FuncId::Allowance => /* ... */,
     FuncId::DiaPriceFeed => /* ... */,
 }
```
With these improvements, the code becomes more comprehensible, maintainable, and follows best practices.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/260?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber
