### ISSUE TITLE
Audit: PDM-011 - Logging in Runtime

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/pendulum#262]
The implementation of ChainExtension contains a lot on unnecessary `warn!()` macros.

ID PDM-011
Scope Logging
Status New

**Description**
Upon reviewing the runtime code, it was observed that numerous instances of the `warn!()` macro are present. While the warn macro can be useful during testing or debugging phases, it is unnecessary in the final version of the code. These superfluous warn macros clutter the codebase and can impede code readability and maintenance.
Unneeded logging statements add noise to the code and distract developers from critical information. In the absence of proper justification, excessive logging can obscure important log messages and make it more challenging to identify and address genuine issues.

**Recommendation**
To enhance the code quality and maintainability of the runtime, we recommend refining the use of warn macros. By limiting the use of these macros to critical and important situations, the codebase will become more concise and easier to comprehend. This targeted approach will enable developers to focus on essential log messages that offer meaningful insights into the system's behavior, rather than being overwhelmed by extraneous warnings. Therefore, unnecessary warn macros should be reviewed and removed, with a priority on retaining only those that provide critical and important warnings.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/262?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber

**Comment by TorstenStueber** [comment]
I am not sure whether we should remove the macros in general but instead of removing them it might be more reasonable to replace them with `trace`.

**Comment by ebma** [comment]
> I am not sure whether we should remove the macros in general but instead of removing them it might be more reasonable to replace them with trace.

Sounds good. Having some kind of message would still be nice IMO
