### ISSUE TITLE
Audit: PDM-001 - Pendulum build

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/pendulum#263]
The Pendulum chain demonstrates a smooth and error-free build process.

ID PDM-001
Scope Build Process
Status New

**Description**
 The build process for the Pendulum chain is efficient and error-free. When executing the `cargo build --release` command, the output confirms a successful build with only one minor compiler warning related to an unused import. The build process adheres to sound Rust coding practices and follows idiomatic conventions.
During the assessment, it was observed that the `orml-currencies-allowance-extension` pallet is not included as a member of the workspace, although it should be.

**Recommendation**
To address this issue, we recommend adding `pallets/orml-currencies-allowance-extension` to the members list in the main `Cargo.toml` file of the workspace.
Please note that this issue does not encompass the results of linting tools, such as Clippy , which may provide additional warnings and recommendations for improving code quality. These will be addressed separately in PDM-002.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/263?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber

**Comment by b-yap** [comment]
Already added in the members list since July. See [Hugo's PR](https://github.com/pendulum-chain/pendulum/commit/5b922a210b2a6705d3ea6fefbf67b317698f7b80#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R12)
