### ISSUE TITLE
Audit: PDM-005 - Superfluous Implementation of Hooks Trait

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/pendulum#264]
The Hooks trait has been declared in the `orml-currencies-allowance-extension` pallet, but no custom implementations have been provided.

ID PDM-005
Scope Code Quality
Status New

**Description**
The following code snippet raises concerns: `pallets/orml-currencies-allowance-extension/src/lib.rs:99`:
```
 #[pallet::hooks]
impl<T: Config> Hooks<T::BlockNumber> for Pallet<T> {}
```
The Hooks trait is typically used to perform logic on every block initialization, finalization, and other specific actions. However, in the case of the `orml-currencies-allowance-extension` pallet, no methods from the Hooks trait are implemented. While this does not cause any immediate detrimental effects, it can reduce code readability and increase complexity.

**Recommendation**
To improve code clarity and readability, it is recommended to eliminate the use of the Hooks trait in the orml-currencies-allowance- extension pallet. Since no custom implementations are provided, removing the Hooks trait declaration will simplify the code and remove unnecessary complexity.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/264?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber
