### ISSUE TITLE
Add and configure asset registry pallet

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#275]
We should add an asset registry pallet to our runtimes so that we can automate the creation of asset mappings for the [global asset registry](https://github.com/colorfulnotion/xcm-global-registry/tree/main).
We should go for the `orml-asset-registry` pallet as it works well with the `orml-tokens` pallet we use.

This is related to [this](https://github.com/pendulum-chain/tasks/issues/75) ticket.

**Comment by ebma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/275?planning-poker) with Zenhub @TorstenStueber

**Comment by TorstenStueber** [comment]
I assume that we will go for orml-asset-registry?

**Comment by ebma** [comment]
>  I assume that we will go for orml-asset-registry?

Right, I should have mentioned that in the description. Added it now.
