### ISSUE TITLE
Inaccuracy in Approve Chain Extension behavior

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/pendulum#281]
While implementing the weight charging for the token allowance pallet, I noticed that the `approve` behavior isn't consistent with OpenZeppelin's one. 

#### 1) The current behavior *increments* the approval, whereas it should *overwrite*. 

See Docs: https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#IERC20-approve-address-uint256-

Current behavior: https://github.com/pendulum-chain/pendulum/blob/0f6cbb5289d03bd85ab664e7724aba691fea8d81/pallets/orml-currencies-allowance-extension/src/lib.rs#L208C3-L208C3

Expected behavior: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/21bb89ef5bfc789b9333eb05e3ba2b7b284ac77c/contracts/token/ERC20/ERC20.sol#L345
Fixing this should also result in a lower gas cost when regenerating the weights. (no longer need to read before writing)

#### 2) When approved for the max possible amount, `transfer_from` should treat it as infinity and not decrement it. 
See Docs: https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20-approve-address-uint256-

**Comment by ashneverdawn** [comment]
While implementing the weight charging for the token allowance pallet, I noticed that the `approve` behavior isn't consistent with OpenZeppelin's one. 


1) The current behavior **increments** the approval, whereas it should **overwrite**. 
See: https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#IERC20-approve-address-uint256-

Current behavior: https://github.com/pendulum-chain/pendulum/blob/0f6cbb5289d03bd85ab664e7724aba691fea8d81/pallets/orml-currencies-allowance-extension/src/lib.rs#L208C3-L208C3

Expected behavior: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/21bb89ef5bfc789b9333eb05e3ba2b7b284ac77c/contracts/token/ERC20/ERC20.sol#L345

Fixing this should also result in a lower gas cost when regenerating the weights. (no longer need to read before writing)


2) When approved for the max possible amount, `transfer_from` should treat it as infinity and not decrement it. See: https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20-approve-address-uint256-

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/281?planning-poker) with Zenhub @ashneverdawn @TorstenStueber
