### ISSUE TITLE
Add testnet USDC threshold to Foucoco

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#285]
When setting up the new genesis for Foucoco in #282 we included most of the already defined currency thresholds for the vault registry but forgot to include the most important one, which is the testnet USDC. 

For some context: We re-added the currencies that existed for on-chain of our old Foucoco to the genesis of the 'new' one. These currencies replicate the currencies that we defined for Amplitude, because we used Foucoco to dry-run the transaction that added these currencies to Spacewalk on Amplitude. These are mainnet assets and thus not bridgable on Foucoco, but it's not problematic that we have defined thresholds for them on-chain.

However, we of course need to have thresholds for the testnet USDC because that's the main token we want to test with on Foucoco.

**Comment by ebma** [comment]
I used the following extrinsic call data for performing a sudo transaction on Foucoco.
```
0x0c003302104509010002015553444314d19631b03717d9ab9a366e10321ee266e72ec76cab6190f0a1336d48229f8b0000a0d8855734160000000000000000450b010002015553444314d19631b03717d9ab9a366e10321ee266e72ec76cab6190f0a1336d48229f8b00003d9160e458110000000000000000450a010002015553444314d19631b03717d9ab9a366e10321ee266e72ec76cab6190f0a1336d48229f8b00008c1d95cc6d1300000000000000004508010002015553444314d19631b03717d9ab9a366e10321ee266e72ec76cab6190f0a1336d48229f8b00203d88792d00000000000000000000
```

The update was applied in block 12,979.

**Comment by ebma** [comment]
@pendulum-chain/product this ticket is fixing a problem related to getting Spacewalk back up and running how it was before the Foucoco reset. I'm not sure to which epic I should assign it, maybe you know better.

**Comment by vadaynujra** [comment]
@annatekl since all current effort for Spacewalk is part of the next milestone i.e. public launch on Amplitude, could you add this to the appropriate ticket and add the `unexpected` label
