### ISSUE TITLE
Investigate User Unable to Unstake

### ISSUE THREAD

**Issue by LeoFraq** [pendulum-chain/pendulum#300]
A member of our community has been unable to unstake his entire balance from both the Portal and Penguin, and received the following error:

`"Transaction failed with errors: parachainStaking.DelegationBelowMin: The account has not staked enough funds to delegate a collator candidate."`

The extrinsic does not seem to have run from [polkaholic](https://polkaholic.io/account/6juiCWRg628yGQEJ4WFJb3yYPd7yGRAZk8ggqm1hZAGXkznW?group=overview&chainfilters=all)

Investigate as to whether the issue arises from the Portal, or from the Extrinsic

Full conversation, [here](https://satoshipay.slack.com/archives/CHKP63SDV/p1692182723289229)

**Comment by prayagd** [comment]
This is an older ticket, the feature works now. Closing this ticket.
