### ISSUE TITLE
Add `clients-info` crate for Spacewalk to Foucoco and Amplitude runtime

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#305]
In order for our Spacewalk vault clients to be able to automatically update, we need to add a pallet that stores information about the latest releases on-chain. The pallet will be created as part of [this](https://github.com/pendulum-chain/tasks/issues/46) task and has to be added and configured for our Spacewalk-supported runtimes. (ie. Foucoco and Amplitude).

This ticket is related to https://github.com/pendulum-chain/tasks/issues/46.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/305?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber
