### ISSUE TITLE
Research the farming smart contract for Nabla

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum#306]
## Context 
In order to distribute farming rewards to Nabla LP providers, we need to research the farming smart contract shared from the Nabla team. 

## Requirements
* Can this smart contract be transpiled to WASM?
* Can we use the transpiled smart contract as is or do we need to write additional code for it?
* What are the parts smart contract need to rewritten?

## Note
Smart contract - https://github.com/0xlaozi/qidao/blob/main/contracts/StakingRewards.sol

## Research
Refer to [this](https://www.notion.so/satoshipay/23-10-25-Smart-Contract-for-Farming-Rewards-467ea92c0b5f4e49987fe74266af9a11) Notion page.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/306?planning-poker) with Zenhub @adelarja @b-yap @ebma @TorstenStueber

**Comment by TorstenStueber** [comment]
Where is this coming from? I though that Nabla is self-contained and sufficient for our needs, I did not expect that we need to deploy other smart contracts.

**Comment by prayagd** [comment]
@TorstenStueber this is for distributing rewards for farming LP tokens, the Nabla smart contracts does not include this. This is an additional one.

**Comment by ebma** [comment]
@gianfra-t I can see that this ticket is in the review column but it doesn't mention any research document in the description. Can you please update it so that it reflects the current state?

**Comment by gianfra-t** [comment]
Sorry, I forgot to add it here. The research is [in this notion page](https://www.notion.so/satoshipay/23-10-25-Smart-Contract-for-Farming-Rewards-467ea92c0b5f4e49987fe74266af9a11)

**Comment by prayagd** [comment]
@ebma i see we need to use a `SafeERC20` library to make the smart contract compatible with Pendulum. Should the followup ticket be deployment of that farming smart contract along with the `SafeERC20` library?

**Comment by ebma** [comment]
> Should the followup ticket be deployment of that farming smart contract along with the SafeERC20 library?

Yes, if you want to have the farming feature, then the follow-up ticket should be about deploying the farming contract mentioned in this ticket together with the `SafeERC20` contract used by Nabla.
