### ISSUE TITLE
EURC added to Pendulum network

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum#310]
We need to add a new asset on Pendulum - EURC

This would be part of our runtime and go through a governance proposal (referendum to include new asset).

**Comment by gianfra-t** [comment]
Hey @annatekl. It seems I miss-clicked and finalized the estimate. Is it possible to reset it? Nobody had voted yet.

**Comment by annatekl** [comment]
done @gianfra-t

**Comment by ebma** [comment]
@annatekl what exactly is this ticket about? What does 'adding a new asset' mean to you?

**Comment by annatekl** [comment]
@ebma you are right, its an old ticket.
