### ISSUE TITLE
Add the new Spacewalk pallets

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#314]
This ticket is a part of https://github.com/pendulum-chain/tasks/issues/47

Spacewalk adds two new pallets:
* pooled-rewards
* reward-distribution

These pallets should be added to the Foucoco and Amplitude implementation of Spacewalk and should use the following configuration parameters:

## Pooled rewards
* set `PoolId` configuration to `CurrencyId`
* set `StakeId` configuration to `AccountId`

## Reward-distribution
* set `Currency` to pallet-balances

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/314?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber
