### ISSUE TITLE
Enable Pendulum assets to be transferable via XCM

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/pendulum#315]
### Context
As part of the XCM channel opened with Pendulum and other parachains, the PEN, USDC, BRL, XLM, TZS, and EURC tokens need to be transferred seamlessly via XCM. This will enable their utilization in various ways, including the option to lock them for minting other assets. 

### User Story
As a holder of PEN, USDC, BRL, XLM, TZS, and EURC tokens, I must be able to transfer these tokens to other parachains (that have enabled these assets) so that I can fully utilize these tokens as needed.

### Task

Update XCM pallet ([inspiration from Interlay](https://github.com/interlay/interbtc/blob/90a5c1b707c00dc9035c7ab438a7db3c8e651c19/parachain/runtime/interlay/src/xcm_config.rs#L327)) such that the following assets are transferable to Polkadot parachains with open XCM channels:
- [ ] Native: PEN, EURC
- [ ] Spacewalk: USDC / BRL / XLM /  TZS

_**Consider:**_ 
_- Enable PEN to be transferred to any parachain, not just Equilibrium._
_- Enable future native tokens (e.g. EURC) to be transferable to other parachains (e.g. Moonbeam)_

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/315?planning-poker) with Zenhub @adelarja @b-yap @ebma @TorstenStueber @gianfra-t

**Comment by TorstenStueber** [comment]
@bogdanS98 As discussed yesterday, this ticket is a "quick fix" ticket that does not require to install the xc registry pallet but is just to add PEN directly to the CurrencyId <-> MultiLocation conversion function.

The Multilocation should just be a reference to pallet-balances.

**Comment by ebma** [comment]
Let's also add this change to all our runtimes and not just Pendulum. All of them should be able to transfer their native token via XCM to connected parachains (and are not able to do so yet).
