### ISSUE TITLE
SBP: Handle fees

### ISSUE THREAD

**Issue by NachoPal** [pendulum-chain/pendulum#34]
Fees are not yet handled: [https://github.com/pendulum-chain/pendulum/blob/master/runtime/src/lib.rs#L411](https://github.com/pendulum-chain/pendulum/blob/master/runtime/src/lib.rs#L411)

**Comment by TorstenStueber** [comment]
We addresses this in our new main branch where we added a runtime definition for our Kusama chain "Amplitude": https://github.com/pendulum-chain/pendulum/blob/1d142c645632d87d8cba03461a66c6edd8c5b082/runtime/amplitude/src/lib.rs#L372.

**Comment by TorstenStueber** [comment]
@NachoPal Feel free to close this ticket if this addresses this issue.
