### ISSUE TITLE
Implement rewards for Spacewalk public launch on Amplitude 

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum#346]
This ticket is to define the reward distribution for public vaults on Amplitude. 

### Assumptions:
- Total vault income comprises fees (wrapped tokens) and PEN rewards.
- Capacity is determined by the allowed issuance based on provided collateral (Collateral amount / Secure collateralization factor 160%).

Vault rewards structure:
- Total income for vaults is in fees (wrapped tokens) + PEN rewards. Since issue and redeem fee is initially zero, the reward pot will only contain minted tokens. 
- Reward is defined for each collateral based on the USD value in the pool (distributed proportionally)
- main approaches and technical considerations as per [ticket](https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/tasks/47)

### Approach:
- Fixed PEN/Block/Month, decreasing monthly.
- Total allocation: 12,000,000 AMPE tokens distributed over 24 months.
- Decay rate: 3.75674% for AMPE, calculated to meet the target allocation.
- Initial month's allocation: 750,000 AMPE i.e. 750,000/(number of blocks in a month), followed by a decay rate of 3.75674% for each subsequent month until 24 months

### Distribution:
- Rewards distributed proportionally to the fraction of the stake of a vault.
- Assets are converted to USD, and rewards are distributed based on the USD value of the vault's stake.

The rewarding mechanism aims to encourage active participation of vault operators in the Spacewalk ecosystem, fostering a healthy and sustainable network.

## TODO
Extrinsics to call:
- [set_reward_per_block](https://github.com/pendulum-chain/spacewalk/blob/82f9e432490b85234f16538b996c589e6af4146e/pallets/reward-distribution/src/lib.rs#L171-L172) with a reward of ??? AMPE per block
- For every wrapped asset that we support, we again need to call `set_secure_collateral_threshold()` with the threshold that is already defined. Calling this is necessary though, because this extrinsic was changed to also add the wrapped currency used in the threshold to the list of rewards currencies, see [here](https://github.com/pendulum-chain/spacewalk/blob/82f9e432490b85234f16538b996c589e6af4146e/pallets/vault-registry/src/lib.rs#L404).
- set issue and redeem fee to 0%
- set the system_collateral_ceiling for all currencies to 10_000 KSM (ie 10_000_000_000_000)

**Comment by annatekl** [comment]
@ebma do you need any more technical details? I linked the ticket with technical considerations

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/346?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
@pendulum-chain/product for this transaction we need to set the reward per block, can you provide that as well?

**Comment by annatekl** [comment]
@ebma we will use the formula  750,000/(number of blocks in a month), followed by a decay rate of 3.75674%

**Comment by annatekl** [comment]
@ebma we will use the formula  750,000/(number of blocks in a month), followed by a decay rate of 3.75674%

**Comment by vadaynujra** [comment]
Decay rate is applied every month.

**Comment by ebma** [comment]
Okay so if I understand correctly, you want to have an initial reward of 750,000 AMPE per month which decays every month. I was asking about the reward per block though, so assuming a month of 30 days, we would have
60 * 60 = 3,600 seconds in an hour, 24 * 3,600 = 86,400 seconds in a day, 30 * 86,400 = 2,592,000 seconds in a month, and if the block time is 12 seconds, then the number of blocks produced in a month is 2,592,000 / 12 = 216,000 blocks.
Thus 750,000/216,000 = 3.47222222222 AMPE per block?

If you agree please update the description of the ticket.

**Comment by annatekl** [comment]
@ebma ticket updates

**Comment by ebma** [comment]
@vadaynujra I just realized that for our rewards mechanism, we intended to set the issue and redeem fee to 0.00%, right? At the moment, the issue and redeem fee are still set to 0.1%. We can change this as part of this transaction as well.

**Comment by vadaynujra** [comment]
@ebma good point and let's update that if we can.

**Comment by TorstenStueber** [comment]
@annatekl What is the status of this ticket, is it not required for the public launch that happened this week?

**Comment by annatekl** [comment]
@TorstenStueber not for now, we want to see if vaults are joining and providing collateral without rewards

**Comment by ebma** [comment]
@pendulum-chain/product do we want to set the collateral ceiling now to a reasonable number or the maximum available number? Any new opinions here?

**Comment by annatekl** [comment]
@ebma  lets go with reasonable number yet high (10 000 KSM per asset)

**Comment by ebma** [comment]
Closing this because the transaction was executed.
