### ISSUE TITLE
Add bifrost farming pallet to the Pendulum runtime

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum#351]
## Context 

With the success of the generic AMM (Zenlink) on Amplitude, there is a business need to implement it on Pendulum. The bifrost farming pallet was already added and [configured](https://github.com/pendulum-chain/pendulum/blob/f5e92519105706925f7e9da6fae18079a3833017/runtime/foucoco/src/lib.rs#L1371-L1380) for the Foucoco and Amplitude runtime a while ago. 

## To-do
Add Bifrost's farming pallet and configure it the same way it is configured in the Amplitude runtime

## Acceptance Criteria

- Root user can create new pools for existing assets

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/351?planning-poker) with Zenhub @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/351?planning-poker) with Zenhub @bogdanS98

**Comment by gianfra-t** [comment]
Since we are still blocked on [this](https://github.com/pendulum-chain/tasks/issues/74) issue, should we also wait for that? I imagine that some things may have changed in the configuration and it would perhaps be double work to implement it first with our fork and then later change it to the original.

**Comment by ebma** [comment]
But are we blocked by that issue? The farming pallet is already added to the Amplitude and Foucoco runtime, so we can just add the same configuration to Pendulum as well. 
We'd need to change that eventually, once the other ticket is done, but I don't think that this poses a significant overhead.

**Comment by gianfra-t** [comment]
Okay then! I will add it to Pendulum.
