### ISSUE TITLE
Perform runtime upgrade for Pendulum release 10

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/pendulum#355]
## Context
This runtime upgrade is to enable the native PEN transfer and enable the bifrost farming pallet on Pendulum network, which would further unblock LP farming for upcoming PEN-DOT listing

### Parameters
* Council led
* Fast track to complete within 3 hours

### Title: Authorize runtime upgrade to Pendulum release 10

Purpose of the referendum is to make the native token PEN transferrable through XCM and add the Bifrost farming pallet to Pendulum runtime.

For all details and new features related to this release, see Github release page.

1. Enabling PEN to be transferrable through XCM to other parachains
2. Adding Bifrost farming pallet to Pendulum runtime, which would further unblock LP farming on Zenlink

This referendum is a significant step forward in the development and growth of the network.

**Comment by prayagd** [comment]
@TorstenStueber the description is not visible here some Github, please check actual ticket on Github for the parameters and required description.

**Comment by TorstenStueber** [comment]
I created the release and the council motion.

Release: https://github.com/pendulum-chain/pendulum/releases/tag/pendulum-release-10
Council motion: https://pendulum.polkassembly.io/motion/14
