### ISSUE TITLE
Add ERC20 and oracle chain extension to Amplitude and Pendulum

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#356]
The chain extension developed for Foucoco that contains the code used by the ERC20 wrapper contracts and the oracle wrapper contract should also be added to Amplitude and Pendulum.

It might makes sense to deduplicate code and move the chain extension into runtime/common, however, we should carefully check what effects this can have and whether the code is compatible with all three runtimes.

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/356?planning-poker) with Zenhub @ebma @bogdanS98 @b-yap @gianfra-t

**Comment by TorstenStueber** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/356?planning-poker) with Zenhub @TorstenStueber

**Comment by ebma** [comment]
@TorstenStueber we already have a ticket to extract and re-use the chain extension [here](https://github.com/pendulum-chain/pendulum/issues/249). Since we want to have this chain extension on Pendulum very soon, I'd suggest we duplicate the code for now and extract and deduplicate it in a follow-up PR for the other ticket.

**Comment by b-yap** [comment]
Are there any specific operations that should be done, in order to test this change?

**Comment by ebma** [comment]
Hmm you could try uploading the wrapper contract for the native token in zombienet and call some functions on it. Then we know whether it works.
[erc20wrapper.zip](https://github.com/pendulum-chain/pendulum/files/13675358/erc20wrapper.zip)
