### ISSUE TITLE
Handle delegation of BRZ token to automation pallet in XCM config

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#358]
## Context

The overall context for this is described in [this](https://www.notion.so/satoshipay/Automating-BRZ-EUR-on-Pendulum-4037d39f0b434a5ab2e299195b228b33) Notion page.

When receiving an XCM transfer of BRZ tokens from Moonbeam that targets our [automation pallet](https://github.com/pendulum-chain/pendulum/issues/357), we need to transfer the received BRZ tokens to the on-chain account of the automation pallet and call a function on it.

## Implementation

We need to change the XCM config of our runtime so that it:
1) is able to convert the `MultiLocation` of the incoming BRZ transfer from Moonbeam to a BRZ asset
2) deposits the received tokens into the account of the automation pallet (exposed by its `getPalletAccount()` function)
3) calls the `processEurcOfframp()` function on the pallet

#### Location of the BRZ asset on the `CurrencyId` enum

The BRZ asset is represented by `CurrencyId::XCM(4)`, see [here](https://github.com/pendulum-chain/pendulum/blob/da17c6641f147ac6fd6406607c594dd2f6f049ae/runtime/pendulum/src/assets.rs#L10).

#### MultiLocation
The `MultiLocation` of the incoming BRZ transfer will have the following form:
```
MultiLocation: {
    parents: 1,
    interior: { X3: { 
       Parachain(2094),
       PalletInstance(xx), // will point to the automation pallet
       GeneralKey{ length: xx, data: []  }, // this will hold the reference number for Mykobo
},
```

#### Intercepting the XCM call

Since the `MultiLocation` of the incoming transfer needs to be handled a little different to other tokens, ie. the recipient account is defined by the automation pallet and we need to add extra logic so that we call the `processEurcOfframp()` function on the automation pallet for these transfers, it would be best to find some way to intercept the call entirely and not go down the usual route defined in the [FungiblesTransactor](https://github.com/pendulum-chain/pendulum/blob/da17c6641f147ac6fd6406607c594dd2f6f049ae/runtime/pendulum/src/xcm_config.rs#L150).

It is not clear yet how exactly we need to change the types used in our XCM config to achieve this. Figuring this out is part of this ticket.

#### Passing the reference number

The `processEurcOfframp()` function needs to be called with the reference number that is contained in the `MultiLocation`. It is not clear yet how this reference number is going to look like so we need to use a placeholder for now.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/358?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
