### ISSUE TITLE
SBP: Polkadot/Substrate version

### ISSUE THREAD

**Issue by NachoPal** [pendulum-chain/pendulum#36]
Bump to the latest Substrate/Polkadot version

**Comment by b-yap** [comment]
I believe this ticket was raised when the version was still `0.9.18` 
Pendulum is now using version `polkadot-v0.9.24` : see [commit](https://github.com/pendulum-chain/pendulum/commit/aca99326f870aaea62b048bc7b296d0b11ad116b#diff-6431a3eec6e102bbcffb94387cda89efbe02002649745273fb575234c0018de4). If that's okay, we can close this issue.
