### ISSUE TITLE
Enable Pendulum assets to be transferable via XCM

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum#360]
#### Context
As part of the XCM channel opened with Pendulum and other parachains, the USDC, BRL, XLM, TZS, NGNC / EURC (Spacewalk) / AUDD and tokens need to be transferred seamlessly via XCM. This will enable their utilization in various ways, including the option to lock them for minting other assets.

#### User Story
As a holder of USDC, BRL, XLM, TZS, AUDD, NGNC and EURC tokens, I must be able to transfer these tokens to other parachains (that have enabled these assets) so that I can fully utilize these tokens as needed.

#### Task
Update XCM pallet ([inspiration from Interlay](https://github.com/interlay/interbtc/blob/90a5c1b707c00dc9035c7ab438a7db3c8e651c19/parachain/runtime/interlay/src/xcm_config.rs#L327)) such that the following assets are transferable to Polkadot parachains with open XCM channels:

Spacewalk: USDC / BRL / XLM / TZS / NGNC / EURC / AUDD

**Comment by ebma** [comment]
I removed the 'consider' block from the description as it didn't fit here.

**Comment by vadaynujra** [comment]
Since we're talking about Spacewalk bridged assets being transferable via XCM, would this only be possible once Spacewalk is actually live on Pendulum and these assets also exist? Or can the provisioning for the assets to be transferable, already possible @ebma @bogdanS98?

**Comment by ebma** [comment]
We can already add the logic for them being transferable, no problem. Before Spacewalk is live on Pendulum none of these assets will be minted so you practically cannot transfer them anyways. 
But now that you mention it, this ticket only talks about Pendulum. Should we also make Spacewalk assets transferrable via XCM on Amplitude or not?

**Comment by annatekl** [comment]
updated the description and removed EURC (native) as already is transferable to other parachains. Moving to icebox as this is required at a later stage when we launch spacewalk on Pendulum

**Comment by vadaynujra** [comment]
@annatekl no that Spacewalk is live on Pendulum and assets have been bridged, this ticket should be able to be progressed and also tested?

**Comment by gianfra-t** [comment]
Since we modified the asset registry and corresponding code in the runtime to read it, these assets should be transferable already if the receiving chain accepts them. The fee for these assets is in the metadata of the chain.

**Comment by TorstenStueber** [comment]
@pendulum-chain/product what is still left to be done here? Shouldn't that all work now?

**Comment by ebma** [comment]
@pendulum-chain/product when are we testing?

**Comment by annatekl** [comment]
I can test XLM, EURC after they are registered on Astar, their team started to work on it last week @ebma

**Comment by ebma** [comment]
Let's test this again once PEN and XLM.s are registered on the Astar portal.

**Comment by TorstenStueber** [comment]
Are the assets registered on the Astar portal now and can we continue here?

**Comment by annatekl** [comment]
the assets were already moved via XCM to Astar team for testing purposes. What is only pending is assets being added to Astar portal.

**Comment by TorstenStueber** [comment]
Does this mean that this ticket here is done and we can close it?

**Comment by prayagd** [comment]
dont have the full context here but based on earlier messages, i propose to close
