### ISSUE TITLE
Add integration test for transferring DEV token via XCM

### ISSUE THREAD

**Issue by bogdanS98** [pendulum-chain/pendulum#371]
### ~~TODO~~

- ~~Add integration test to test transfer of DEV token (added in https://github.com/pendulum-chain/pendulum/issues/366) to sibling chain (Moonbase Alpha mock) and back~~

This will be **closed** because Foucoco DEV transfers **to** and **from** Moonbase Alpha are successful but the integration test fails due to some misconfiguration of the sibling parachain. Finding the exact issue with the sibling chain's XCM config is not worth the effort at this moment. Another issue is that making the sibling chain work for this particular integration test requires its id to be the same as Moonbase Alpha (1000) which takes some thoughtful refactoring of the current setup in order not to break the other integration tests that use id 1000 for AssetHub.

**Comment by bogdanS98** [comment]
Closing reason in the description.

**Comment by prayagd** [comment]
@bogdanS98 Can you please add estimates?
