### ISSUE TITLE
XCM transfer of native currency does not work

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#376]
At the moment, the XCM transfer of our native currency does not work. One of (possibly many) reasons is that the `AssetTransactor` of the `xcm_executor` pallet config only supports interacting with the `Tokens` pallet right now, but we need to extend it such that it either uses the `Balances` pallet for our native currency or the `Tokens` pallet for all else.

There might be other issues with the XCM config though, which have to be identified when solving this issue.

**Comment by TorstenStueber** [comment]
Can we just use the `Currencies` pallet, which unifies `Tokens` and `Balances`?
