### ISSUE TITLE
Add clippy to CI

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#384]
It would probably be beneficial to add clippy checks, as they are [disabled](https://github.com/pendulum-chain/pendulum/blob/58d806850b912e22905c444d99db7a9b0757df98/.github/workflows/test-code.yml#L48-L50) right now. We can use the same [rules](https://github.com/pendulum-chain/spacewalk/blob/a5cc81ececb9a464fc8caa12c191eeaecf453c4b/.github/workflows/ci-main.yml#L80-L91) we already use in Spacewalk.

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/384?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by TorstenStueber** [comment]
Also note that there is this ticket, which we could add as well: https://github.com/pendulum-chain/spacewalk/issues/153

**Comment by prayagd** [comment]
@TorstenStueber closing this one as we have already have a duplicate one which is prioritized

**Comment by prayagd** [comment]
@TorstenStueber you already mentioned in the above comments https://github.com/pendulum-chain/spacewalk/issues/153 or are they different tickets?

**Comment by TorstenStueber** [comment]
Sorry, I missed that. Thanks.

**Comment by TorstenStueber** [comment]
I will open this ticket here. The other ticket is in a different repository and therefore we need separate tickets.
