### ISSUE TITLE
Add custom metadata and parameters for asset registry

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#392]
We want to store a `fee_per_second` attribute for each asset defined in our asset registry. For this, we want to use the [CustomMetadata](https://github.com/pendulum-chain/pendulum/blob/54f466074384689e34d3e5af920884a230ea10a4/runtime/pendulum/src/lib.rs#L749) of the asset registry. At the moment, we are using the [CustomMetadata](https://github.com/pendulum-chain/pendulum/blob/54f466074384689e34d3e5af920884a230ea10a4/runtime/common/src/asset_registry.rs#L10) struct defined in the spacewalk primitives but it makes more sense to now define this struct in our runtimes instead.

## TODO
- Create a `CustomMetadata` struct that replaces the one in [asset_registry](https://github.com/pendulum-chain/pendulum/blob/54f466074384689e34d3e5af920884a230ea10a4/runtime/common/src/asset_registry.rs#L10)
- Add a `fee_per_second` parameter to it
- Add parameters for price oracle keys. We should create a new struct `DiaKeys { blockchain: Vec<u8>, symbol: Vec<u8> }` that allows using this info to create price info from our DIA oracle pallet.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/392?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
