### ISSUE TITLE
Create `testnet` runtime

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/pendulum#41]
The runtime of our testnet resides in the branch `pendulum-legacy`.
The aim of this issue is to include this runtime in the main branch, under the folder `runtime/testnet`.
Of course that besides the runtime itself, we need to include dependencies and related files.
Also, bump dependencies to version 0.9.24

**Comment by ebma** [comment]
This can probably be closed because it is irrelevant now and we also have foucoco as our 'testnet' by now.
