### ISSUE TITLE
Investigate 'Transaction has a bad signature' error on Foucoco

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#411]
We are currently facing issues with the following error message in our spacewalk testing-service and faucet service which are trying to submit extrinsics on **Foucoco**:
```
## Faucet Service
2024-02-13 14:00:50        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature

## Testing Service
2024-02-13 23:32:06        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature
2024-02-13 23:32:06        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature
RpcError: 1010: Invalid Transaction: Transaction has a bad signature
    at file:///app/spacewalk-testing-service/dist/vault_service/vault.js:50:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/spacewalk-testing-service/dist/vault_service/vault.js:18:13 {
  extrinsicCalled: 'Issue Request',
  sender: '6kmmmu4nTuELg5xXqLvfK9TzMsUgmqZEX4iGpMXmQWm71271'
}
```

We don't know the reason yet, but it seems to have first appeared on Feb 6, see [this](https://satoshipay.slack.com/archives/C05PW684QK1/p1707175932893069) reported incident. I think at that time we redeployed the collator nodes on Foucoco so it might be related to that collator redeployment. This would mean that there were pending changes to the node which were only applied after the redeployment. But this is not certain. 

Submitting extrinsics still seems to work with polkadot.js explorer. So we have to assume that extrinsic submission is only broken when done programmatically (ie. when done with the `api` exposed by the polkadot.js npm package).

## TODO
We can try to boil down the problem by testing the following:
- Try to submit an extrinsic on Foucoco via polkadot.js explorer and programmatically with the polkadot.js package. For this, you can try to create and submit a very basic transaction with the transaction-builder repository. Here, we want to test if even very simple extrinsics (like transferring tokens) fail when done programmatically. 
- Try to run Foucoco locally in zombienet and see if the same error is thrown when submitting transactions programmatically.

**Comment by ebma** [comment]
@pendulum-chain/product we are facing some issues with extrinsic submissions on Foucoco so we are investigating in this ticket.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/411?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by TorstenStueber** [comment]
Was there a runtime upgrade in between? The signature of a transaction is not just over the transaction itself but uses more signing material, such as the current spec version and transaction version. A transaction created before a runtime upgrade will have an invalid signature if executed after a runtime upgrade.

This happens in 
* the [runtime executive](https://github.com/paritytech/substrate/blob/98f2e3451c9143278ec53c6718940aeabcd3b68a/frame/executive/src/lib.rs#L556)
* which calls the [`check` function](https://github.com/paritytech/substrate/blob/98f2e3451c9143278ec53c6718940aeabcd3b68a/primitives/runtime/src/generic/unchecked_extrinsic.rs#L137-L151) of `UncheckedExtrinsic`
* which adds [all additional signing material from all signed extensions](https://github.com/paritytech/substrate/blob/98f2e3451c9143278ec53c6718940aeabcd3b68a/primitives/runtime/src/generic/unchecked_extrinsic.rs#L195)
* and the [`CheckSpecVersion`](https://github.com/pendulum-chain/pendulum/blob/eb45880e002e4750f7e616618ff82db33c9ffc5f/runtime/pendulum/src/lib.rs#L131) and [`CheckTxVersion`](https://github.com/pendulum-chain/pendulum/blob/eb45880e002e4750f7e616618ff82db33c9ffc5f/runtime/pendulum/src/lib.rs#L132) will add the spec and transaction versions

I also suggest to check whether any of the other signed extensions provides signing material that is unexpected by the chain. Maybe easiest to rerun the block with blockchain but use a locally compiled version of the runtime with extra log output (see [here](https://www.notion.so/satoshipay/23-07-05-Forking-live-chains-with-Chopsticks-ad5a3f85257d445697a1dadcdfbdd500?pvs=4#45eeff2e946e443c9df339fc783e9404)).

**Comment by ebma** [comment]
The fix was simpler than we thought. All we had to do was restart both the testing service and faucet and the error was gone(thanks @gianfra-t for the idea). The problem was probably related to the fact that the `api` objects are cached and re-used in both services. As you pointed out @TorstenStueber, we probably executed a runtime upgrade in the meantime which made the cached `api` object unable to create valid signatures. 

With this in mind, we can close this ticket as completed but I'll create follow-up tickets to add handling for this case to the services.
