### ISSUE TITLE
Switch to 'stable' rust toolchain channel

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#444]
At the moment, we are using the 'nightly' channel of the Rust toolchain. Going forward, we want to use the 'stable' channel because some tools like the SRTool don't work on 'nightly' anymore, at least not on the latest versions, see [this](https://github.com/paritytech/srtool/issues/62) issue. 

Switching the toolchain was not possible before as we encountered compiler errors. It might be that the recent update of the polkadot dependencies to v0.9.42 resolves those problems.

## TODO
Change the `rust-toolchain.toml` to use a 'stable' channel. Make sure that all runtimes and integration tests still compile and work as expected.

**Comment by b-yap** [comment]
@pendulum-chain/product After the [findings](https://github.com/pendulum-chain/tasks/issues/170#issuecomment-2042488599) I had today, this has to be done first.
