### ISSUE TITLE
Replace OracleKey enums used in treasury-buyout-extension

### ISSUE THREAD

**Issue by bogdanS98** [pendulum-chain/pendulum#445]
### Context

At this moment, `treasury-buyout-extension` is using `oracle` pallet from Spacewalk to fetch asset prices. Since `CustomMetadata` struct containing DIA keys was added to our runtimes, we can use `dia-oracle` pallet directly for this use case.

### Requirement

Modify `PriceGetter` implementation for all runtimes so that it uses DIA fields from `CustomMetadata` struct instead of `OracleKey` [enum](https://github.com/pendulum-chain/pendulum/blob/dd8eb3d55ac2933bfc375a13b7a9d2d73ca4ea86/runtime/pendulum/src/lib.rs#L1409-L1410).

Note: DIA fields should be checked if they are empty.

**Comment by bogdanS98** [comment]
@pendulum-chain/product This is not urgent but nice to have.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/445?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
