### ISSUE TITLE
Implement `--version` command

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#456]
Ensure that the node clients return the version number, see this message from a third party collator:

> is it possible to have versioning on collators binaries? so when we use ./amplitude-collator --version we get the correct node version and also it will be displayed on telemetry correctly, so you can check for every provider which version is running

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/456?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t

**Comment by ebma** [comment]
This ticket also entails updating our version numbers in all `Cargo.toml` files, doesn't it? Is this something we should talk about @TorstenStueber? Like, when do we want to bump to new major, minor, or patch versions? Or do we want to keep this number aligned to something else?

**Comment by TorstenStueber** [comment]
Mmhh, I did not think about this. Just thought that the version number could just be the version of the runtime. But that would not really be correct...

Then it probably makes sense to track the version of the client in the `Cargo.toml` of the client. We would then need to define a scheme for version numbers.

**Comment by gianfra-t** [comment]
I think the [current](https://docs.substrate.io/reference/command-line-tools/node-template/) `node-template` already has this `--version` flag. Not sure what it returns, but it is likely that the person was referring to this. If this is the case we should modify the client to return the same to be consistent with later versions.

**Comment by TorstenStueber** [comment]
Yes, that would make sense.

**Comment by ebma** [comment]
As far as I know, our node binaries also already support the `--version` flag but it's currently quite useless as we don't update the version in the `Cargo.toml` files which is probably the main concern of the external operators.

**Comment by TorstenStueber** [comment]
Okay, so the right solution would just be to add the workflow that for every client release we actively bump the version and nothing else would need to be done here ....
