### ISSUE TITLE
Change chain extensions to return transferable balance

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum#483]
## Context
Related to this [ticket](https://github.com/pendulum-chain/portal/issues/485). Fixes to be made so that Nabla modals should show up as transferrable balance. 

Our chain extension exposes functions conforming to the ERC-20 interface. In ERC-20, the only function to get the balance of an address is using the `balanceOf()` call. At the moment, we are returning the 'free' balance of a user, see [here](https://github.com/pendulum-chain/pendulum/blob/991c7694084c22ee61716723d001163e746a1725/chain-extensions/token/src/lib.rs#L181). However, the `free_balance` is not necessarily the transferable balance, as it does not take into account the locked or reserved tokens. 

See the relation of the `system::account()` query to the transferable amount. 
<img width="604" alt="image" src="https://github.com/pendulum-chain/pendulum/assets/6690623/6e7fe0fe-1ad4-49dd-b19e-d5e475ea1251">

<img width="314" alt="image" src="https://github.com/pendulum-chain/pendulum/assets/6690623/8c731bae-d76d-417a-87de-ae6b44460fed">

## TODO

Change the `balance_of` function of the chain extension to return the transferable amount ie. `free - reserved - frozen`.

**Comment by prayagd** [comment]
@ebma Please fill in the details

**Comment by ebma** [comment]
I updated the description @prayagd.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/483?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by vadaynujra** [comment]
Does this only apply to when the native asset (PEN) is part of Nabla @ebma ?

**Comment by TorstenStueber** [comment]
No, it applies to all assets.

**Comment by TorstenStueber** [comment]
I think it is actually good to implement this soon, now that Nabla will be live on Pendulum.
