### ISSUE TITLE
RPCs not compliant with the JSON-RPC spec

### ISSUE THREAD

**Issue by josepot** [pendulum-chain/pendulum#503]
Dear Pendulum Team,

I hope this message finds you well. My name is Josep, and I'm the technical lead of the [Polkadot-API (PAPI)](https://papi.how/) team.

In case you're not familiar with Polkadot-API, it's a modern library designed to replace PolkadotJS, built on top of a properly specified and [standardized JSON-RPC API](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead.html) for Polkadot-based networks. The modern JSON-RPC APIs offer many advantages over the legacy ones; you can read more about it [here](https://paritytech.github.io/json-rpc-interface-spec/objectives.html) and [here](https://forum.polkadot.network/t/new-json-rpc-api-mega-q-a/3048#why-do-we-need-a-new-json-rpc-api-9).

We've noticed that there are no available public Pendulum RPCs that expose the modern JSON-RPC API.  Thankfully, it's still possible to use PAPI with Pendulum thanks to the light-client provider, using the following chainspec with smoldot:

```json
{
  "name": "Pendulum",
  "id": "pendulum",
  "chainType": "Live",
  "bootNodes": [
    "/dns4/penawsuse-collator-00.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWPfFVdVqSb8vaZLvkWCDxkuvhLu3S9cX8soQpQNzUyLD9",
    "/dns4/penawsuse-collator-01.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWNWauGnqHbFxfAg7Z9e8Zr1apnp5CacRAL9MG9Fin9PxG",
    "/dns4/penawsuse-collator-02.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWJ9LpJLXbtTVzoFDa92x4szwcUCHZAj7EFzm7tVEv6jX9",
    "/dns4/penawsuse-collator-03.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWQ4ZVdm5mxQz6ubH2mwZHmEahy3dP6tVZWmJzUmFnZc2H",
    "/dns4/penctbsyd-collator-00.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWDMRjvK63jat9r8fe1mLmXcCKwH3zw2oGZyJfCNFFmDor",
    "/dns4/penctbsin-collator-00.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWAqbWpvqjP5XqhN5X34y2URWa925EaZRaukxDpfokYa4G",
    "/dns4/penctbusw-collator-00.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWFN9eu5r5RRA9v2AA9NJnwLU4akX9i1pw41ni6835feDf",
    "/dns4/penctbeur-collator-00.prd.pendulumchain.tech/tcp/30335/p2p/12D3KooWBVtsdFV8cLG7o2mVXNRMcRVrW463aCVQYU6v1atQNPwt"
  ],
  "properties": {
    "ss58Format": 56,
    "tokenDecimals": 12,
    "tokenSymbol": "PEN"
  },
  "relay_chain": "polkadot",
  "para_id": 2094,
  "codeSubstitutes": {},
  "genesis": {
    "stateRootHash": "0x81f7716029f03ee0bbc13213c77da9fad18273dd737031a6ddc90cd4161a1230"
  }
}
```

However, not all consumers can utilize the light-client.

Our team has developed a [middleware solution](https://papi.how/requirements#polkadot-sdk-110--x--1110) to ensure that Polkadot-API can function seamlessly with chains running older versions of the Polkadot-SDK node. Unfortunately, it appears that the RPC providers for Pendulum are using an even older version, which the middleware does not support.

We kindly request that you consider working with your RPC providers to upgrade the PolkadotSDK node to a more modern version that supports the new JSON-RPC API. This upgrade would enable DApp developers to easily interact with your chain using PAPI, unlocking benefits such as improved performance, reduced resource usage, out-of-the-box strong type generation for your chain, and the ability for developers to handle runtime upgrades on the fly.

Thank you for your time and consideration.

Best regards,

Josep

**Comment by ebma** [comment]
Hey Josep. Thanks a lot for reaching out and making us aware of this problem. Fortunately, we were already in the process of upgrading our runtimes to use the PolkadotSDK dependencies v1.1.0. The runtime upgrade went live on Pendulum just yesterday and the collator nodes were upgraded as well.

If I understood the requirements correctly, clients should now be able to connect to Pendulum with PAPI and the compatibility layer in `polkadot-sdk-compat`? It will probably take us quite some time until we can upgrade the PolkadotSDK dependencies to v1.11.0 or higher, unfortunately. 

@josepot please confirm that this ticket can be considered solved for now and feel free to close it if that's the case.

**Comment by josepot** [comment]
> @josepot please confirm that this ticket can be considered solved for now and feel free to close it if that's the case.

I just re-run the script that checks the status of each chain, and [Pendulum appears green](https://github.com/polkadot-api/compliant-RPCs/blob/9d38c817e99ace9f9dd6f29cc8fedd3a070029a6/results/polkadot.txt#L239)! 🎉 

Thanks!

PS: Also, I noticed that your chain is on metadata v15, which means that PAPI it's going to work even better with your chain 🙂
