### ISSUE TITLE
Launch on public Rococo testnet

### ISSUE THREAD

**Issue by erasmus** [pendulum-chain/pendulum#51]
See [Parity docs for more information](https://docs.substrate.io/tutorials/connect-other-chains/rococo-slot/)

- [x]  Create a new chainspec in Pendulum, that uses the same Amplitude runtime
- [x]  Create new test accounts (with subkey or polkadotjs)
- [x]  Post the keypairs in Notion so everyone can test
- [x]  Generate chain spec raw json file, publish it under res/rococo.json
- [x]  Generate new genesis and wasm files
- [x]  Upload parathread
- [x]  Open an issue in [this](https://github.com/paritytech/subport) repo. Use the same ParaId as Amplitude: `2124`

**Comment by b-yap** [comment]
> Generate chain spec raw json file, publish it under res/rococo.json
  
--> done: https://github.com/pendulum-chain/pendulum/pull/50

> Post the keypairs in Notion so everyone can test

--> done: https://www.notion.so/satoshipay/Testnet-secrets-902325ba81764a3484ec27e1b4f0ad59#7bf6a927f9394e69b6b518f761aa2e5a
