### ISSUE TITLE
Configure polkadot-launch

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/pendulum#6]
Follow the steps here https://github.com/paritytech/polkadot-launch to configure the config files we need to use polkadot-launch.
This way we optimize the testing workflow and gain speed

**Comment by xiuxiu62** [comment]
Just made a pr to resolve this, let me know if there are any other features you'd like in the config.

**Comment by gonzamontiel** [comment]
Development of this was moved to another repo: https://github.com/pendulum-chain/pendulum-launch. So closing this issue.

**Comment by xiuxiu62** [comment]
Okay great, Marcel updated the example config and I made a good deal of progress.  I'm aiming to have it stabilized and usable by tomorrow.
