### ISSUE TITLE
Remove the development runtime

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#80]
Feedback from SBP Milestone 3 review: The development runtime name is a bit misleading, as it seems that this is not merely a runtime for developers to use locally, but the Pendulum runtime intended for future deployment on Polkadot.

## New Description
Let us just remove the development runtime all together.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/80?planning-poker) with Zenhub @adelarja @ebma @TorstenStueber @b-yap @ashneverdawn

**Comment by ebma** [comment]
@TorstenStueber would you consider this ticket still relevant? Maybe we should remove the development runtime altogether as we never used it.

**Comment by b-yap** [comment]
>  would you consider this ticket still relevant? Maybe we should remove the development runtime altogether as we never used it.

I agree.

**Comment by TorstenStueber** [comment]
Yes, I don't even remember why it is there and think that we never use it. I think I/we originally intended it to be a standalone version of Foucoco/Amplitude/Pendulum to make it easy to run relevant components locally. But with Zombienet that would not be necessary anymore.

**Comment by ebma** [comment]
Agreed, this is nice to have and very low effort. I'll move it out of the icebox and into the 'ready' column because implementing this should be quick @pendulum-chain/product.
