### ISSUE TITLE
Add and configure Spacewalk pallets for Foucoco runtime

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum#88]
Since we want to launch Spacewalk on Amplitude, we need to include and configure the pallets in the Amplitude runtime. Before taking this step on Amplitude it might make sense however to first test the changes and upgrade on Foucoco. 

This issue is about adding all the pallets included in [spacewalk/pallets](https://github.com/pendulum-chain/spacewalk/tree/dev/milestone-3/pallets) to the foucoco and amplitude runtime. Since they are not merged to `main`, it makes sense to declare the `dev/milestone-3` branch in the 'Cargo.toml' files. Eventually, we would probably create an extra `polkadot-v0.9.35` branch in the spacewalk repository, but only after merging it to `main`. Inspiration for the appropriate configuration of the pallets can be drawn from the `mock.rs` files of each pallet in the spacewalk repository.

**Comment by ebma** [comment]
This requires #87.

**Comment by ebma** [comment]
I split this ticket into two separate tasks since it is probably a good idea to work on the Foucoco runtime first. The other ticket is #90.

**Comment by b-yap** [comment]
launched last Friday, at block 4,056,711
