### ISSUE TITLE
Add chain extension for DIA oracles

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#92]
Once pallet-contracts is implemented, add a chain extension for making quotes from the DIA oracle pallet available to smart contracts.

**Comment by erasmus** [comment]
@TorstenStueber can we move to done or assign to another milestone?

**Comment by RustNinja** [comment]
@erasmus once we merge this [pull request ](https://github.com/pendulum-chain/pendulum/pull/163) to main branch we will close it.
