### ISSUE TITLE
Upgrade the DIA oracle pallet to polkadot-v0.9.37

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/pendulum#95]
- [ ] Crete a PR in https://github.com/diadata-org/oracle-pallet that updates the code in the pallet to support `polkadot-v0.9.36` version
- [ ] Update the dependencies in this repo to use the updated version

**Comment by ebma** [comment]
We updated the dependency in our forked repository, see [here](https://github.com/pendulum-chain/oracle-pallet/commit/825c33715902450398b9c704ea678cf4478c22e9)
