### ISSUE TITLE
Democratization rollout

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum#98]
1. Remove sudo pallet
2. Unlock token transfer transactions
3. Change default pallet weights
4. Update to latest Polkadot version
5. Update the democracy cycle times to:
    1. 5 days launch period
    2. 5 days voting period
    3. 2 days enactment period
    4. 7 days cool off period
6. Add pallets:
    1. ZenLink pallet  
        1. Mandatory / Basic parameters:
            1. `set_fee_point` - 0.5%
            2. `set_fee_to` - Address
            3. `pool currency symbol limit` = 50
    - DIA pallet
    - `pallet-contracts`
    - `identity-pallet`

**Comment by erasmus** [comment]
@TorstenStueber can we move to done?

**Comment by vadaynujra** [comment]
@TorstenStueber can you please respond here?

**Comment by TorstenStueber** [comment]
Yes, done.
